#!/bin/bash

# === MDH ULTRA-POWER SHELL INSTALLER ===
# This script will automatically:
# 1. Back up your existing ~/.bashrc
# 2. Install necessary "hacker" tools.
# 3. Inject the new, powerful configuration.
# 4. Reload your shell.

# --- 1. CONFIGURATION & PREAMBLE ---

# Define colors for the installer script
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# File to modify
BASHRC_FILE="$HOME/.bashrc"
# Backup file location
BACKUP_FILE="$HOME/.bashrc.mdh_backup_$(date +%F-%T)"

# Markers for the config block to make it re-runnable
CONFIG_START_MARKER="# === START MDH ULTRA-POWER SHELL CONFIG ==="
CONFIG_END_MARKER="# === END MDH ULTRA-POWER SHELL CONFIG ==="

# Welcome message for the installer
cat << "EOF"

  __  __  ____  _   _ 
 |  \/  |/ ___|| | | |
 | |\/| | |  _ | |_| |
 | |  | | |_| ||  _  |
 |_|  |_|\____||_| |_|
 
 ULTRA-POWER SHELL INSTALLER

EOF
echo -e "${GREEN}Starting the MDH Ultra-Power Shell setup...${NC}"

# --- 2. INSTALLER FUNCTIONS ---

# Function to install all necessary tools
function install_tools() {
    echo -e "${YELLOW}Updating package lists (this may take a moment)...${NC}"
    sudo apt-get update -y > /dev/null 2>&1

    local tools_to_install="figlet toilet lolcat pv cmatrix neofetch htop bat eza fzf"
    echo -e "${YELLOW}Installing tools: ${tools_to_install}...${NC}"
    
    sudo apt-get install -y $tools_to_install
    
    if [ $? -ne 0 ]; then
        echo -e "${RED}Error: Tool installation failed.${NC}"
        echo -e "${RED}Please run 'sudo apt-get update' and try again.${NC}"
        exit 1
    fi
    
    # Create symlink for 'bat' if 'batcat' is installed (common on Ubuntu)
    if command -v batcat &> /dev/null && ! command -v bat &> /dev/null; then
        echo -e "${YELLOW}Creating symlink for 'batcat' -> 'bat'...${NC}"
        sudo ln -s /usr/bin/batcat /usr/local/bin/bat
    fi
    
    echo -e "${GREEN}Tools installed successfully.${NC}"
}

# Function to back up the .bashrc
function backup_bashrc() {
    echo -e "${YELLOW}Backing up your current $BASHRC_FILE to $BACKUP_FILE...${NC}"
    cp $BASHRC_FILE $BACKUP_FILE
    if [ $? -ne 0 ]; then
        echo -e "${RED}Error: Failed to create backup. Aborting.${NC}"
        exit 1
    fi
    echo -e "${GREEN}Backup created.${NC}"
}

# Function to inject the new configuration
function inject_config() {
    echo -e "${YELLOW}Removing any existing MDH config...${NC}"
    # This sed command removes the block between the markers
    sed -i "/$CONFIG_START_MARKER/,/$CONFIG_END_MARKER/d" $BASHRC_FILE

    echo -e "${YELLOW}Injecting new 'ultra-power' configuration into $BASHRC_FILE...${NC}"
    
    # Use a single-quoted HEREDOC to prevent variable expansion
    cat >> $BASHRC_FILE << 'EOF'

# === START MDH ULTRA-POWER SHELL CONFIG ===
# This block was auto-generated by the MDH installer.

# --- 1. WELCOME ANIMATION (Runs on interactive shell start) ---
# Only run for interactive shells ($- contains 'i') and top-level shell (SHLVL=1)
if [[ $- == *i* && $SHLVL -eq 1 ]]; then
    clear
    
    # "Glitch" animation for MDH
    # -f slant = Font
    # -a = Animate
    # -d 5 = Duration (5 frames)
    # -p 100 = Speed
    toilet -f slant "MDH" | lolcat -a -d 5 -p 100

    echo "" # New line
    
    # "Typing" welcome message
    WELCOME_MSG="Welcome, $(whoami). System online. All modules loaded."
    echo "$WELCOME_MSG" | pv -qL 100 | lolcat -p 7
    echo "------------------------------------------------------------" | lolcat -p 10
    echo "Type 'info' for system details, 'matrix' for fun, or 'll' for files."
    echo "" # New line
fi

# --- 2. "ULTRA" ALIASES ---
# Use 'eza' (a modern 'ls') with icons
alias ls='eza --icons --color=auto --group-directories-first'
alias ll='eza -l --icons --color=auto --group-directories-first'
alias l='eza -lFbhH --icons --color=auto --git --group-directories-first'
alias la='eza -la --icons --color=auto --group-directories-first'

# Use 'bat' (a modern 'cat') with syntax highlighting
alias cat='bat --style=plain'

# Colorize grep
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# "Hacker" aliases
alias matrix='cmatrix -s -b -C cyan' # -C cyan = set color to cyan
alias info='neofetch' # System info
alias myip='curl ifconfig.me ; echo' # Get public IP
alias htop='htop' # Better process manager
alias find='fzf' # Use fzf for finding (use Ctrl+T for files)

# Git aliases
alias ga='git add'
alias gc='git commit -m'
alias gs='git status'
alias gp='git push'
alias gpl='git pull'
alias gl='git log --oneline --graph --decorate'

# --- 3. THE "ULTRA-POWER" PROMPT (PS1) ---
# Define colors for the prompt
RED='\[\033[01;31m\]'
GREEN='\[\033[01;32m\]'
YELLOW='\[\033[01;33m\]'
BLUE='\[\033[01;34m\]'
MAGENTA='\[\033[01;35m\]'
CYAN='\[\033[01;36m\]'
WHITE='\[\033[01;37m\]'
NC='\[\033[00m\]' # No Color

# Function to get Git branch
parse_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ ('$MAGENTA'\1'$NC')/'
}

# Function to build the prompt. This runs before every prompt.
build_prompt() {
    local exit_code=$? # Get last command's exit code
    local prompt_symbol
    
    # Set prompt symbol color based on exit code
    if [ $exit_code -eq 0 ]; then
        prompt_symbol="$GREEN❯$NC" # Green ❯ for success
    else
        prompt_symbol="$RED❯$NC" # Red ❯ for failure
    fi
    
    # --- Assemble the PS1 String ---
    # Line 1: [user@host] (Cloud_Project_ID)
    PS1="$RED\u@\h$NC "
    PS1+="$CYAN(\$CLOUD_SHELL_PROJECT_ID)$NC"
    
    # Line 2: └──[directory][git_branch] ❯
    PS1+="\n"
    PS1+="$WHITE└──$NC $BLUE\w$NC" # Directory
    PS1+="\$(parse_git_branch)" # Git branch
    PS1+=" $prompt_symbol " # Prompt symbol
}

# Register 'build_prompt' to run before each prompt
PROMPT_COMMAND="build_prompt"

# Enable fzf keybindings
[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# === END MDH ULTRA-POWER SHELL CONFIG ===
EOF

    if [ $? -ne 0 ]; then
        echo -e "${RED}Error: Failed to inject configuration. Aborting.${NC}"
        echo -e "${RED}Your original .bashrc is safe in $BACKUP_FILE${NC}"
        exit 1
    fi
}

# --- 3. EXECUTION ---

main() {
    install_tools
    backup_bashrc
    inject_config

    echo -e "${GREEN}Configuration injected successfully.${NC}"
    echo -e "${BLUE}All done! Reloading your shell to apply changes...${NC}"
    echo -e "${WHITE}If you ever want to uninstall, restore from your backup file: $BACKUP_FILE${NC}"
    
    # Reload the shell to apply changes immediately
    exec bash
}

# Run the main function
main
